resources:
- name: sonar-scanner-source
  type: git
  source: 
    uri: https://github.com/emerald-squad/sonar-scanner-net.git
    branch: 'master'
    ignore_paths:
    - README.md
    - VERSION
    - ci/pipeline.yml

- name: version
  type: semver
  source: 
    driver: git
    uri: git@github.com:emerald-squad/sonar-scanner-net.git
    branch: 'master'
    file: VERSION
    private_key: ((github-key))


- name: docker-hub
  type: docker-image
  source:
    repository: emeraldsquad/sonar-scanner-net
    username: ((docker-hub-username))
    password: ((docker-hub-password))

jobs:
- name: publish-major-rc
  plan:
  - put: version
    params:
      bump: major
      pre: rc
  - get: sonar-scanner-source
  - put: docker-hub
    params:
      build: sonar-scanner-source
      tag: version/version
      tag_as_latest: false

- name: tag-major-as-final-latest
  plan:
  - get: docker-hub
    passed: [ publish-major-rc ]
    params:
      save: true
  - put: version
    params:
      bump: final
  - put: docker-hub
    params:
      load: docker-hub
      tag: version/version
      tag_as_latest: true

- name: publish-minor-rc
  plan:
  - put: version
    params:
      bump: minor
      pre: rc
  - get: sonar-scanner-source
  - put: docker-hub
    params:
      build: sonar-scanner-source
      tag: version/version
      tag_as_latest: false

- name: tag-minor-as-final-latest
  plan:
  - get: docker-hub
    passed: [ publish-minor-rc ]
    params:
      save: true
  - put: version
    params:
      bump: final
  - put: docker-hub
    params:
      load: docker-hub
      tag: version/version
      tag_as_latest: true

- name: publish-patch-rc
  plan:
  - put: version
    params:
      bump: patch
      pre: rc
  - get: sonar-scanner-source
  - put: docker-hub
    params:
      build: sonar-scanner-source
      tag: version/version
      tag_as_latest: false

- name: tag-patch-as-final-latest
  plan:
  - get: docker-hub
    passed: [ publish-patch-rc ]
    params:
      save: true
  - put: version
    params:
      bump: final
  - put: docker-hub
    params:
      load: docker-hub
      tag: version/version
      tag_as_latest: true

groups:
- name: major
  jobs:
  - publish-major-rc
  - tag-major-as-final-latest

- name: minor
  jobs:
  - publish-minor-rc
  - tag-minor-as-final-latest

- name: patch
  jobs:
  - publish-patch-rc
  - tag-patch-as-final-latest
